/**:
  ros__parameters:
    avoidance:
      avoidance:
        lateral:
          avoidance_execution_lateral_threshold: 0.4158383869930034
          lateral_collision_margin: 0.22910455969947996
          lateral_collision_safety_buffer: 0.19996653286024232
          lateral_passable_safety_buffer: 0.13273564001313415
          max_left_shift_length: 5.0
          max_right_shift_length: 5.0
          road_shoulder_safety_margin: 0.114117605308045
        longitudinal:
          longitudinal_collision_safety_buffer: 1.8698357524729978
          min_avoidance_distance: 4.362290726843311
          min_nominal_avoidance_speed: 7.0
          min_prepare_distance: 0.4890856920952583
          min_sharp_avoidance_speed: 1.0
          prepare_time: 0.8542104835223779
      constraints:
        lateral:
          max_lateral_jerk: 5.3419458456787545
          nominal_lateral_jerk: 42.57589809076688
        longitudinal:
          max_avoidance_acceleration: 0.5
          max_deceleration: -2.0
          max_jerk: 1.0
          min_avoidance_speed_for_acc_prevention: 3.0
          nominal_deceleration: -1.0
          nominal_jerk: 0.5
        use_constraints_for_decel: false
      detection_area_left_expand_dist: 1.0
      detection_area_right_expand_dist: 0.0
      disable_path_update: false
      drivable_area_left_bound_offset: 0.0
      drivable_area_right_bound_offset: 0.0
      enable_avoidance_over_opposite_direction: true
      enable_avoidance_over_same_direction: true
      enable_bound_clipping: false
      enable_force_avoidance_for_stopped_vehicle: true
      enable_safety_check: false
      enable_update_path_when_object_is_gone: true
      enable_yield_maneuver: false
      object_envelope_buffer: 0.1676346515866356
      print_debug_info: false
      publish_debug_marker: true
      resample_interval_for_output: 0.5
      resample_interval_for_planning: 0.1
      safety_check:
        safety_check_accel_for_rss: 2.5
        safety_check_backward_distance: 100.0
        safety_check_hysteresis_factor: 2.0
        safety_check_idling_time: 1.5
        safety_check_time_horizon: 10.0
      stop:
        max_distance: 7.5
        min_distance: 7.5
      target_filtering:
        object_check_backward_distance: 2.0
        object_check_force_avoidance_clearance: 30.0
        object_check_forward_distance: 150.0
        object_check_goal_distance: 20.0
        object_check_min_road_shoulder_width: 0.5
        object_check_shiftable_ratio: 0.6
        object_last_seen_threshold: 2.0
        threshold_distance_object_is_on_center: 0.0
        threshold_speed_object_is_stopped: 1.0
        threshold_time_force_avoidance_for_stopped_vehicle: 1.0
        threshold_time_object_is_moving: 1.0
      target_object:
        bicycle: false
        bus: true
        car: true
        motorcycle: false
        pedestrian: false
        trailer: true
        truck: true
        unknown: true
      target_velocity_matrix:
        col_size: 2
        matrix:
        - 2.78
        - 13.9
        - 0.5
        - 1.0
      yield:
        yield_velocity: 2.78
