/**:
  ros__parameters:
    avoidance:
      enable_module: true
      enable_simultaneous_execution: false
      max_module_size: 1
      priority: 3
    backward_length_buffer_for_end_of_pull_out: 5.0
    backward_length_buffer_for_end_of_pull_over: 5.0
    backward_path_length: 5.0
    expected_front_deceleration: -1.0
    expected_front_deceleration_for_abort: -1.0
    expected_rear_deceleration: -1.0
    expected_rear_deceleration_for_abort: -2.0
    forward_path_length: 25.14203047084035
    lane_change:
      enable_module: true
      enable_simultaneous_execution: false
      max_module_size: 1
      priority: 4
    lateral_distance_max_threshold: 2.0
    longitudinal_distance_min_threshold: 3.0
    minimum_pull_over_length: 16.0
    path_interval: 0.11081105851288707
    planning_hz: 10.0
    pull_out:
      enable_module: true
      enable_simultaneous_execution: false
      max_module_size: 1
      priority: 0
    pull_over:
      enable_module: true
      enable_simultaneous_execution: false
      max_module_size: 1
      priority: 1
    rear_vehicle_reaction_time: 2.0
    rear_vehicle_safety_time_margin: 1.0
    refine_goal_search_radius_range: 7.5
    side_shift:
      enable_module: true
      enable_simultaneous_execution: false
      max_module_size: 1
      priority: 2
    turn_signal_intersection_angle_threshold_deg: 15.0
    turn_signal_intersection_search_distance: 30.0
    turn_signal_minimum_search_distance: 10.0
    turn_signal_on_swerving: true
    turn_signal_search_time: 3.0
    turn_signal_shift_length_threshold: 0.3
    verbose: false
    visualize_maximum_drivable_area: true
